config/routes.rb
Rails.application.routes.draw do
  # Authentication
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'auth/signout', to: 'sessions#destroy', as: 'signout'

  # Shopping List
  get 'shopping-list', to: 'shopping#index', as: 'shopping_list'
  get 'shopping-list/add-new', to: 'shopping#create', as: 'add_new_list'

  root to: 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  # used in sessions#create for omniauth
  def self.from_omniauth(auth)
    
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider         = auth.provider
      user.uid              = auth.uid
      user.name             = auth.info.name
      user.oauth_token      = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])

    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController

  def index
  end

  def create
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Condado</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="cn-navbar" class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_url %>"><%= image_tag "gollum.jpg", width: 30, class: 'img-circle' %> O Condado</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">

    <% if current_user %>
    <p class="pull-right navbar-text">
      <img src="http://graph.facebook.com/<%= current_user.uid %>/picture" alt="" class="img-circle"> Signed in as <strong><%= current_user.name %></strong>! <a href="<%= signout_url %>">Sign out</a>
    </p>
    <% end %>

    <ul class="nav navbar-nav">
      <li><a href="<%= root_url %>">Home</a></li>
      <li></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<div class="container">


	<%= yield %>
</div>
	
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

app/views/shopping/create.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="cn-title">Add New Shopping List <small>Let's fill this shit! Today is <%= Time.now.day %>/<%= Time.now.month %>.</small></h2>
  </div>

  <form action="" class="cn-form">
    <input type="text" class="cn-input" placeholder="You want give it a name?">

    <h2 class="cn-title">Products</h2>
  
    <div class="cn-product">
      <input type="text" class="cn-input cn-input-sm cn-product-name" placeholder="Product Name">

      <a href="#" class="cn-trash hide"><i class="fa fa-trash"></i></a>
    </div> <!-- .cn-product -->

    <div class="cn-alert alert alert-info">
      <small><strong>Tip:</strong> If you press ENTER, the product'll be saved. You still can edit it.</small>

      <div class="clearfix"></div>
      <small><strong>Tip:</strong>Ah, if you want to accoplate some specific brand, just put the name between quotes (""). The Condado will understand. We rock, bitches!</small>
    </div> <!-- .cn-alert -->

  </form>
</div>

app/views/shopping/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="cn-title">Shopping List <small>Because spend some money rocks!</small></h2>
  </div>

  <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
    <div class="thumbnail cn-shopping-new-list cn-shopping-list text-center">
      <p><strong class="cn-date">29/<span class="month">12</span></strong></p>
      <p class="items">Let's fill this shit!</p>
      <p><a href="<%= add_new_list_url %>" class="cn-btn btn btn-block btn-xs btn-default">Add New List</a></p>
    </div>
  </div>

  <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
    <div class="thumbnail cn-shopping-list text-center">
      <p><strong class="cn-date">15/<span class="month">12</span></strong></p>
      <p class="items">Feijão, Arroz, Macarrão and other 7</p>
      <p><a href="#" class="cn-btn cn-btn-clone btn btn-block btn-default btn-xs">Clone this</a></p>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% if current_user %>
  <div class="row">
  
    <div class="col-lg-2 col-md-4 col-sm-6 col-xs-12">

      <div class="cn-thumbnail-gray thumbnail">

        <div class="caption">
          <p><a href="<%= shopping_list_url %>" class="cn-btn btn btn-block btn-default cn-btn-gray">Shopping List</a></p>
        </div> <!-- .caption -->

      </div> <!-- .thumbnail -->

    </div> <!-- .col -->

    <div class="col-lg-2 col-md-4 col-sm-6 col-xs-12">

      <div class="cn-thumbnail-orange thumbnail">

        <div class="caption">
          <p><a href="#" class="cn-btn btn btn-block btn-default cn-btn-orange">House Cleaning</a></p>
        </div> <!-- .caption -->

      </div> <!-- .thumbnail -->

    </div> <!-- .col -->

    <div class="col-lg-2 col-md-4 col-sm-6 col-xs-12">

      <div class="cn-thumbnail-green thumbnail">

        <div class="caption">
          <p><a href="#" class="cn-btn btn btn-block btn-default cn-btn-green">Movies to Watch</a></p>
        </div> <!-- .caption -->

      </div> <!-- .thumbnail -->

    </div> <!-- .col -->
    
    <div class="col-lg-2 col-md-4 col-sm-6 col-xs-12">

      <div class="cn-thumbnail-blue thumbnail">

        <div class="caption">
          <p><a href="#" class="cn-btn btn btn-block btn-default cn-btn-blue">Decoration Shit</a></p>
        </div> <!-- .caption -->

      </div> <!-- .thumbnail -->

    </div> <!-- .col -->
    
    <div class="col-lg-2 col-md-4 col-sm-6 col-xs-12">

      <div class="cn-thumbnail-purple thumbnail">

        <div class="caption">
          <p><a href="#" class="cn-btn btn btn-block btn-default cn-btn-purple">Financial Shit</a></p>
        </div> <!-- .caption -->

      </div> <!-- .thumbnail -->

    </div> <!-- .col -->
    
    <div class="col-lg-2 col-md-4 col-sm-6 col-xs-12">

      <div class="cn-thumbnail-red thumbnail">

        <div class="caption">
          <p><a href="#" class="cn-btn btn btn-block btn-default cn-btn-red">Wishlist</a></p>
        </div> <!-- .caption -->

      </div> <!-- .thumbnail -->

    </div> <!-- .col -->

  </div> <!-- .row -->
<% else %>
<strong>Seja bem vindo!</strong>

<p>Para usufruir do nosso aplicativo, você precisa autenticar-se com o Facebook.</p>

<a href="/auth/facebook" class="cn-btn btn btn-primary btn-lg"> <i class="fa fa-facebook"></i> Conectar com Facebook</a>
<% end %>